version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  pocketbase:
    build:
      context: .
      dockerfile: utils/pocketbase/Dockerfile
    container_name: pocketbase
    ports:
      - "8090:8090"
    # volumes:
    #   - ./pb_data:/pb_data
    environment:
      - POCKETBASE_DEBUG=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
